display_name: Easy Flatpak
icon: export/rpm/512x512.png
summary: An application to simplify install of some flatpak
group: Applications/Development Tools
vendor: Michael Bertocchi
packager: Michael Bertocchi
packagerEmail: imikado@gmail.com
license: LGPLv2.0
url: https://github.com/imikado/dupotEasyFlatpak

build_arch: x86_64

requires:
  - flatpak
  - zenity
  - sqlite
  - sqlite-devel
  - tar

keywords:
  - flatpak
  - store

generic_name: Easy Flatpak

categories:
  - Utility

startup_notify: true
