display_name: Easy Flatpak
package_name: easyflatpak

maintainer:
  name: Michael Bertocchi
  email: imikado@gmail.com

priority: optional

section: x11

installed_size: 21336

dependencies:
  - flatpak
  - zenity
  - sqlite3
  - libsqlite3-dev
  - tar

essential: false

icon: export/deb/512x512.png

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - flatpak
  - store

generic_name: Easy Flatpak

categories:
  - Utility

startup_notify: true
